[2023-11-21T00:49:28.276+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-21T00:49:28.280+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-21T00:49:28.281+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:49:28.286+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-15 00:00:00+00:00
[2023-11-21T00:49:28.293+0000] {standard_task_runner.py:57} INFO - Started process 298 to run task
[2023-11-21T00:49:28.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp51305_kz']
[2023-11-21T00:49:28.300+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask load_data
[2023-11-21T00:49:28.344+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:49:28.399+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-21T00:49:31.576+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:49:31.608+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231115T000000, start_date=20231121T004928, end_date=20231121T004931
[2023-11-21T00:49:31.643+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:49:31.675+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T01:04:27.004+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-21T01:04:27.012+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-21T01:04:27.013+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T01:04:27.084+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-15 00:00:00+00:00
[2023-11-21T01:04:27.127+0000] {standard_task_runner.py:57} INFO - Started process 314 to run task
[2023-11-21T01:04:27.145+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpzgba0nk5']
[2023-11-21T01:04:27.177+0000] {standard_task_runner.py:85} INFO - Job 249: Subtask load_data
[2023-11-21T01:04:27.309+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host e39dda9a9deb
[2023-11-21T01:04:27.450+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-21T01:04:30.739+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T01:04:30.789+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231115T000000, start_date=20231121T010427, end_date=20231121T010430
[2023-11-21T01:04:30.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T01:04:30.920+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
