[2023-11-21T00:40:41.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T00:40:35.152685+00:00 [queued]>
[2023-11-21T00:40:41.540+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T00:40:35.152685+00:00 [queued]>
[2023-11-21T00:40:41.540+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:40:41.545+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_data> on 2023-11-21 00:40:35.152685+00:00
[2023-11-21T00:40:41.553+0000] {standard_task_runner.py:57} INFO - Started process 149 to run task
[2023-11-21T00:40:41.556+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'transform_data', 'manual__2023-11-21T00:40:35.152685+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpq4kezcah']
[2023-11-21T00:40:41.559+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask transform_data
[2023-11-21T00:40:41.589+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T00:40:35.152685+00:00 [running]> on host c6d84631e1b9
[2023-11-21T00:40:41.631+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:40:35.152685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T00:40:35.152685+00:00'
[2023-11-21T00:40:43.093+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:40:43.115+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=transform_data, execution_date=20231121T004035, start_date=20231121T004041, end_date=20231121T004043
[2023-11-21T00:40:43.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:40:43.181+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
