[2023-11-21T02:18:48.813+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T02:18:40.807522+00:00 [queued]>
[2023-11-21T02:18:48.818+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T02:18:40.807522+00:00 [queued]>
[2023-11-21T02:18:48.819+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T02:18:48.824+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_data> on 2023-11-21 02:18:40.807522+00:00
[2023-11-21T02:18:48.832+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2023-11-21T02:18:48.835+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'transform_data', 'manual__2023-11-21T02:18:40.807522+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp7a9nqt5x']
[2023-11-21T02:18:48.838+0000] {standard_task_runner.py:85} INFO - Job 271: Subtask transform_data
[2023-11-21T02:18:48.869+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T02:18:40.807522+00:00 [running]> on host 00029af74441
[2023-11-21T02:18:48.915+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T02:18:40.807522+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T02:18:40.807522+00:00'
[2023-11-21T02:18:50.480+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T02:18:50.512+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=transform_data, execution_date=20231121T021840, start_date=20231121T021848, end_date=20231121T021850
[2023-11-21T02:18:50.555+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T02:18:50.608+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
