[2023-11-21T00:44:12.010+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T00:44:12.014+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T00:44:12.015+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:44:12.026+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-16 00:00:00+00:00
[2023-11-21T00:44:12.035+0000] {standard_task_runner.py:57} INFO - Started process 145 to run task
[2023-11-21T00:44:12.039+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp4qy96_u2']
[2023-11-21T00:44:12.042+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask load_data
[2023-11-21T00:44:12.085+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-16T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:44:12.135+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-21T00:44:15.579+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:44:15.634+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231116T000000, start_date=20231121T004412, end_date=20231121T004415
[2023-11-21T00:44:15.823+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:44:15.921+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T01:00:24.822+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T01:00:24.829+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-16T00:00:00+00:00 [queued]>
[2023-11-21T01:00:24.829+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T01:00:24.847+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-16 00:00:00+00:00
[2023-11-21T01:00:24.872+0000] {standard_task_runner.py:57} INFO - Started process 186 to run task
[2023-11-21T01:00:24.889+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-16T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpy4y6ix1k']
[2023-11-21T01:00:24.894+0000] {standard_task_runner.py:85} INFO - Job 226: Subtask load_data
[2023-11-21T01:00:25.027+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-16T00:00:00+00:00 [running]> on host e39dda9a9deb
[2023-11-21T01:00:25.152+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-16T00:00:00+00:00'
[2023-11-21T01:00:28.811+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T01:00:28.849+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231116T000000, start_date=20231121T010024, end_date=20231121T010028
[2023-11-21T01:00:28.910+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T01:00:28.954+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
