[2023-11-21T00:49:30.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T00:49:30.578+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T00:49:30.578+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:49:30.584+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-14 00:00:00+00:00
[2023-11-21T00:49:30.592+0000] {standard_task_runner.py:57} INFO - Started process 301 to run task
[2023-11-21T00:49:30.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmplaqznj_b']
[2023-11-21T00:49:30.599+0000] {standard_task_runner.py:85} INFO - Job 185: Subtask load_data
[2023-11-21T00:49:30.654+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:49:30.708+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-21T00:49:34.017+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:49:34.062+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231114T000000, start_date=20231121T004930, end_date=20231121T004934
[2023-11-21T00:49:34.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:49:34.176+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T01:09:27.206+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T01:09:27.210+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-21T01:09:27.210+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T01:09:27.216+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-14 00:00:00+00:00
[2023-11-21T01:09:27.221+0000] {standard_task_runner.py:57} INFO - Started process 425 to run task
[2023-11-21T01:09:27.224+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpalyqpqem']
[2023-11-21T01:09:27.227+0000] {standard_task_runner.py:85} INFO - Job 262: Subtask load_data
[2023-11-21T01:09:27.271+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host e39dda9a9deb
[2023-11-21T01:09:27.341+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-21T01:09:30.749+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T01:09:30.781+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231114T000000, start_date=20231121T010927, end_date=20231121T010930
[2023-11-21T01:09:30.842+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T01:09:30.887+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
