[2023-11-21T00:43:57.605+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-21T00:43:57.630+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-21T00:43:57.630+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:43:57.658+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-04 00:00:00+00:00
[2023-11-21T00:43:57.726+0000] {standard_task_runner.py:57} INFO - Started process 133 to run task
[2023-11-21T00:43:57.736+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp9ycwglez']
[2023-11-21T00:43:57.744+0000] {standard_task_runner.py:85} INFO - Job 154: Subtask load_data
[2023-11-21T00:43:57.852+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-04T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:43:57.951+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-21T00:44:01.712+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:44:01.754+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231104T000000, start_date=20231121T004357, end_date=20231121T004401
[2023-11-21T00:44:01.806+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:44:01.853+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T00:59:54.203+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-21T00:59:54.211+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2023-11-21T00:59:54.212+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:59:54.231+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-04 00:00:00+00:00
[2023-11-21T00:59:54.252+0000] {standard_task_runner.py:57} INFO - Started process 141 to run task
[2023-11-21T00:59:54.258+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmphvgttlai']
[2023-11-21T00:59:54.263+0000] {standard_task_runner.py:85} INFO - Job 215: Subtask load_data
[2023-11-21T00:59:54.299+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-04T00:00:00+00:00 [running]> on host e39dda9a9deb
[2023-11-21T00:59:54.359+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2023-11-21T00:59:58.346+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:59:58.360+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231104T000000, start_date=20231121T005954, end_date=20231121T005958
[2023-11-21T00:59:58.401+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:59:58.443+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
