[2023-11-21T00:43:57.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-21T00:43:57.743+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-21T00:43:57.743+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:43:57.761+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-03 00:00:00+00:00
[2023-11-21T00:43:57.779+0000] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2023-11-21T00:43:57.797+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpvrq8jwf4']
[2023-11-21T00:43:57.808+0000] {standard_task_runner.py:85} INFO - Job 155: Subtask load_data
[2023-11-21T00:43:57.904+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-03T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:43:57.994+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-21T00:44:01.711+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:44:01.762+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231103T000000, start_date=20231121T004357, end_date=20231121T004401
[2023-11-21T00:44:01.811+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:44:01.873+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T00:59:52.641+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-21T00:59:52.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-21T00:59:52.651+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:59:52.669+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-03 00:00:00+00:00
[2023-11-21T00:59:52.698+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2023-11-21T00:59:52.710+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp_njdrljh']
[2023-11-21T00:59:52.722+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask load_data
[2023-11-21T00:59:52.849+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-03T00:00:00+00:00 [running]> on host e39dda9a9deb
[2023-11-21T00:59:52.973+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-21T00:59:57.909+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:59:57.934+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231103T000000, start_date=20231121T005952, end_date=20231121T005957
[2023-11-21T00:59:57.962+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:59:57.983+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
