[2023-11-21T00:49:23.105+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T00:42:38.308368+00:00 [queued]>
[2023-11-21T00:49:23.128+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T00:42:38.308368+00:00 [queued]>
[2023-11-21T00:49:23.129+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-21T00:49:23.153+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_data> on 2023-11-21 00:42:38.308368+00:00
[2023-11-21T00:49:23.184+0000] {standard_task_runner.py:57} INFO - Started process 282 to run task
[2023-11-21T00:49:23.204+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'transform_data', 'manual__2023-11-21T00:42:38.308368+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp_3hgfq5r']
[2023-11-21T00:49:23.214+0000] {standard_task_runner.py:85} INFO - Job 178: Subtask transform_data
[2023-11-21T00:49:23.318+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.transform_data manual__2023-11-21T00:42:38.308368+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:49:23.432+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T00:42:38.308368+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T00:42:38.308368+00:00'
[2023-11-21T00:49:25.375+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:49:25.438+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=transform_data, execution_date=20231121T004238, start_date=20231121T004923, end_date=20231121T004925
[2023-11-21T00:49:25.510+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:49:25.580+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
